package com.connecto.app.report

import com.connecto.app.data.SelectionEntity

/**
 * Rule-based sentence generator for the auto-report system.
 * No internet or AI required — works fully offline.
 */
object ReportGenerator {

    fun generateAutoSentences(selections: List<SelectionEntity>): String {
        if (selections.isEmpty()) return "No areas have been selected."

        val sb = StringBuilder()
        sb.append("Patient reports the following:\n\n")

        for ((index, s) in selections.withIndex()) {
            val painStr = if (s.painType.isNotBlank()) "${s.painType} pain" else "discomfort"
            val durStr  = if (s.duration.isNotBlank()) "for ${s.duration}" else ""
            val side    = s.side.lowercase().replaceFirstChar { it.uppercase() }
            val orient  = s.orientation.lowercase().replaceFirstChar { it.uppercase() }

            sb.append("${index + 1}. Patient reports $painStr in the $side ${orient.lowercase()} ${s.commonName} region $durStr.")
            if (s.notes.isNotBlank()) sb.append(" Additional notes: ${s.notes}.")
            sb.append("\n")
        }

        return sb.toString().trim()
    }

    fun generateStructuredReport(
        patientName: String,
        age: String,
        gender: String,
        selections: List<SelectionEntity>,
        date: String
    ): String {
        val sb = StringBuilder()

        sb.appendLine("═══════════════════════════════════════")
        sb.appendLine("         CONNECTO MEDICAL REPORT        ")
        sb.appendLine("═══════════════════════════════════════")
        sb.appendLine()
        sb.appendLine("Patient Name : $patientName")
        sb.appendLine("Age          : $age")
        sb.appendLine("Gender       : $gender")
        sb.appendLine("Date         : $date")
        sb.appendLine()
        sb.appendLine("───────────────────────────────────────")
        sb.appendLine("        AFFECTED REGIONS SUMMARY        ")
        sb.appendLine("───────────────────────────────────────")
        sb.appendLine()

        for ((i, s) in selections.withIndex()) {
            sb.appendLine("${i + 1}. ${s.commonName} (${s.side})")
            sb.appendLine("   Medical Term : ${s.medicalName}")
            sb.appendLine("   Orientation  : ${s.orientation}")
            sb.appendLine("   Pain Type    : ${s.painType.ifBlank { "Not specified" }}")
            sb.appendLine("   Duration     : ${s.duration.ifBlank { "Not specified" }}")
            if (s.notes.isNotBlank()) sb.appendLine("   Notes        : ${s.notes}")
            sb.appendLine()
        }

        sb.appendLine("───────────────────────────────────────")
        sb.appendLine("         AUTO-GENERATED SUMMARY         ")
        sb.appendLine("───────────────────────────────────────")
        sb.appendLine()
        sb.append(generateAutoSentences(selections))
        sb.appendLine()
        sb.appendLine()
        sb.appendLine("═══════════════════════════════════════")
        sb.appendLine("  Generated by CONNECTO — Offline Mode  ")
        sb.appendLine("═══════════════════════════════════════")

        return sb.toString()
    }
}
